### ISSUE TITLE
Option to cache the Parsed Template

### ISSUE THREAD

**Issue by turtl7** [splumhoff/PSMustache#1]
In high frequency use, parsing the same template for each execution is expensive. can there be a caching done for parsed template? internally it could be based on file path input. While externally, caller can cache the parser's outcome and pass it as input in subsequent calls.

**Comment by splumhoff** [comment]
Hi,

please have a look at the new release 1.3.1. I'm very interested if and how much this speeds up your environment.
May I ask how many runs do you take with the same template?

**Comment by splumhoff** [comment]
Hi @turtl7,

did you have time to give the new release a try?

**Comment by splumhoff** [comment]
No response, but should work as described
